#define PS_A "ps -A"
#define PS_AT "ps -AT"
#define TARGET_PROCESS "crackme1"
#define TARGET_WCHAN "compat_SyS_nanosleep"
#define LIBCRACKME "libcrackme1.so"
#define LIBCSO "libc.so"
#define LIBDLSO "libdl.so"
#define LIBCPATH "/apex/com.android.runtime/lib/bionic/libc.so"
#define HIJACKLIBCPATH "/data/local/tmp/evil.so"